# Generated by Django 4.0.2 on 2022-09-14 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('num_star', models.IntegerField(choices=[(1, 'worst'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Best')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.musician')),
            ],
        ),
    ]
